---
version: '3.3'

services :
  front:
    build: ./frontend/.
    env_file:
      - .env
    ports:
      - "3000:3000"
  steam:
    build: ./backend/Update_Steam_Game
#    env:
#      - STEAM_API_KEY:
    ports:
      - "5000:5000"