---
version: '3.3'

services :
  front:
    build: ./frontend/.
    env_file:
      - .env
    ports:
      - "3000:3000"
  steam:
    build: ./backend/Update_Game
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
    ports:
      - "5000:5000"